### ISSUE TITLE
Question: importance of click history

### ISSUE THREAD

**Issue by dfrumkin** [alibaba/ClickSEG#1]
Dear authors, thank you for sharing the code, great work!

I am trying to understand how you use clicks.  It looks like the Segmentor receives the previous mask and up to 20 last clicks in the order they were generated.  The last one is the correction the user is trying to make, whereas the others are historical clicks that led to the previous mask.  Is that correct?

If so, did you find it important to keep the history of clicks for coarse segmentation?  What would happen if you passed only the previous mask and the last click (e.g. like you do later for refinement)?

**Comment by XavierCHEN34** [comment]
you are correct.
The historical clicks are important. If you remove them and only feed the last click + previous mask into the model,  the last click might destroy some correct mask regions guided by the previous clicks.

**Comment by dfrumkin** [comment]
Thank you for your response!  Yes, I've played with the code with and without history and the difference is very significant.
