### ISSUE TITLE
Questions on Datasets

### ISSUE THREAD

**Issue by dfrumkin** [alibaba/ClickSEG#3]
Could you please share your considerations when choosing datasets for training?

- As one option, you use COCO+LVIS.  In the RITM paper, they say that LVIS is the best; however, it has a problem of being "long-tailed and therefore lacking general object categories".  Could you elaborate on the problem from your experience?  For example, if we wanted to achieve way over 90% IoU, wouldn't low-quality COCO annotations be a problem?
- Models trained on a combination of 8 datasets achieve better results that those trained on COCO+LVIS.  Is the reason in higher image diversity (meaning COCO+LVIS is not diverse enough) or that the other 6 datasets have higher-quality annotations than COCO?
- How did you combine those 8 datasets?  For example, did you just add 6 full datasets to the COCO+LVIS combination?
- How long did it take to train on the huge combined dataset?

**Comment by XavierCHEN34** [comment]
1. LVIS do not contain annotations for `stuff'.  Besides, objects is LVIS are usually small in size. Hence, COCO is necessary. And our experiments show that COCO+LVIS is better than LVIS (I did not record the detailed digits).  Although COCO masks are not very fine, they are acceptable to train the  model.

2. I think the both,  but the later one is more important.   For example, ADE20K gives more diverse images. The saliency data sets are finely annotated.

3. We add proportional ratios like in https://github.com/alibaba/ClickSEG/blob/main/models/strongbaseline/mobilenetv2_x1_comb.py#:~:text=%5B0.35%2C0.10%2C0.1%2C0.2%2C0.1%2C0.15%5D%2C

4. Sorry, I have forgotten the  training time.   Maybe 3-5 times longer  than training on COCO+LVIS.

**Comment by dfrumkin** [comment]
Thanks a lot!
