### ISSUE TITLE
ImageNet-pretrained MobileNetv2, etc.

### ISSUE THREAD

**Issue by dfrumkin** [alibaba/ClickSEG#4]
I see you provide ImageNet-pretrained weights for SegFormer and HRNet at https://github.com/alibaba/ClickSEG/blob/main/assets/documents/Data_Weight_Preparation.md#2-download-imagenet-pretrained-weights.  Where can I get those for MobileNetV2 and other models?

I've tried torch.hub; however, they have a different naming convention for blocks.

**Comment by XavierCHEN34** [comment]
mobilenet: https://github.com/LikeLy-Journey/SegmenTron/releases/tag/v0.1.0
pplcnet  https://github.com/frotms/PP-LCNet-Pytorch

**Comment by dfrumkin** [comment]
Thank you very much!
